/*
Kowabunga API documentation

Testing RecordAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kowabunga

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_kowabunga_RecordAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RecordAPIService DeleteDnsRecord", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var recordId string

		httpRes, err := apiClient.RecordAPI.DeleteDnsRecord(context.Background(), recordId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordAPIService ReadDnsRecord", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var recordId string

		resp, httpRes, err := apiClient.RecordAPI.ReadDnsRecord(context.Background(), recordId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordAPIService UpdateDnsRecord", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var recordId string

		resp, httpRes, err := apiClient.RecordAPI.UpdateDnsRecord(context.Background(), recordId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
