/*
Kowabunga API documentation

Testing AdapterAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kowabunga

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_kowabunga_AdapterAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AdapterAPIService DeleteAdapter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var adapterId string

		httpRes, err := apiClient.AdapterAPI.DeleteAdapter(context.Background(), adapterId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdapterAPIService ListAdapters", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AdapterAPI.ListAdapters(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdapterAPIService ReadAdapter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var adapterId string

		resp, httpRes, err := apiClient.AdapterAPI.ReadAdapter(context.Background(), adapterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdapterAPIService UpdateAdapter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var adapterId string

		resp, httpRes, err := apiClient.AdapterAPI.UpdateAdapter(context.Background(), adapterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
