/*
Kowabunga API documentation

Testing NfsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kowabunga

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_kowabunga_NfsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test NfsAPIService DeleteStorageNFS", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var nfsId string

		httpRes, err := apiClient.NfsAPI.DeleteStorageNFS(context.Background(), nfsId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NfsAPIService ListStorageNFSKylos", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var nfsId string

		resp, httpRes, err := apiClient.NfsAPI.ListStorageNFSKylos(context.Background(), nfsId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NfsAPIService ListStorageNFSs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.NfsAPI.ListStorageNFSs(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NfsAPIService ReadStorageNFS", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var nfsId string

		resp, httpRes, err := apiClient.NfsAPI.ReadStorageNFS(context.Background(), nfsId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NfsAPIService UpdateStorageNFS", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var nfsId string

		resp, httpRes, err := apiClient.NfsAPI.UpdateStorageNFS(context.Background(), nfsId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
