/*
Kowabunga API documentation

Testing PoolAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kowabunga

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	
)

func Test_kowabunga_PoolAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test PoolAPIService CreateTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var poolId string

		resp, httpRes, err := apiClient.PoolAPI.CreateTemplate(context.Background(), poolId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoolAPIService DeleteStoragePool", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var poolId string

		httpRes, err := apiClient.PoolAPI.DeleteStoragePool(context.Background(), poolId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoolAPIService ListStoragePoolTemplates", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var poolId string

		resp, httpRes, err := apiClient.PoolAPI.ListStoragePoolTemplates(context.Background(), poolId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoolAPIService ListStoragePoolVolumes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var poolId string

		resp, httpRes, err := apiClient.PoolAPI.ListStoragePoolVolumes(context.Background(), poolId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoolAPIService ListStoragePools", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PoolAPI.ListStoragePools(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoolAPIService ReadStoragePool", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var poolId string

		resp, httpRes, err := apiClient.PoolAPI.ReadStoragePool(context.Background(), poolId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoolAPIService SetStoragePoolDefaultTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var poolId string
		var templateId string

		httpRes, err := apiClient.PoolAPI.SetStoragePoolDefaultTemplate(context.Background(), poolId, templateId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoolAPIService UpdateStoragePool", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var poolId string

		resp, httpRes, err := apiClient.PoolAPI.UpdateStoragePool(context.Background(), poolId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
