/*
Kowabunga API

Testing AgentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kowabunga

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	
)

func Test_kowabunga_AgentAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test AgentAPIService CreateAgent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AgentAPI.CreateAgent(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AgentAPIService DeleteAgent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		httpRes, err := apiClient.AgentAPI.DeleteAgent(context.Background(), agentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AgentAPIService ListAgents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AgentAPI.ListAgents(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AgentAPIService ReadAgent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.AgentAPI.ReadAgent(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AgentAPIService SetAgentApiToken", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.AgentAPI.SetAgentApiToken(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AgentAPIService UpdateAgent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.AgentAPI.UpdateAgent(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
