/*
Kowabunga API

Testing VolumeAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kowabunga

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	
)

func Test_kowabunga_VolumeAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test VolumeAPIService DeleteVolume", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var volumeId string

		httpRes, err := apiClient.VolumeAPI.DeleteVolume(context.Background(), volumeId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VolumeAPIService ListVolumes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VolumeAPI.ListVolumes(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VolumeAPIService ReadVolume", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var volumeId string

		resp, httpRes, err := apiClient.VolumeAPI.ReadVolume(context.Background(), volumeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VolumeAPIService UpdateVolume", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var volumeId string

		resp, httpRes, err := apiClient.VolumeAPI.UpdateVolume(context.Background(), volumeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
