/*
Kowabunga API

Testing KiwiAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kowabunga

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	
)

func Test_kowabunga_KiwiAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test KiwiAPIService DeleteKiwi", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kiwiId string

		httpRes, err := apiClient.KiwiAPI.DeleteKiwi(context.Background(), kiwiId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KiwiAPIService ListKiwis", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.KiwiAPI.ListKiwis(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KiwiAPIService ReadKiwi", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kiwiId string

		resp, httpRes, err := apiClient.KiwiAPI.ReadKiwi(context.Background(), kiwiId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KiwiAPIService UpdateKiwi", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kiwiId string

		resp, httpRes, err := apiClient.KiwiAPI.UpdateKiwi(context.Background(), kiwiId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
