/*
Kowabunga API documentation

Testing KaktusAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kowabunga

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	
)

func Test_kowabunga_KaktusAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test KaktusAPIService DeleteKaktus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kaktusId string

		httpRes, err := apiClient.KaktusAPI.DeleteKaktus(context.Background(), kaktusId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KaktusAPIService ListKaktusInstances", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kaktusId string

		resp, httpRes, err := apiClient.KaktusAPI.ListKaktusInstances(context.Background(), kaktusId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KaktusAPIService ListKaktuss", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.KaktusAPI.ListKaktuss(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KaktusAPIService ReadKaktus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kaktusId string

		resp, httpRes, err := apiClient.KaktusAPI.ReadKaktus(context.Background(), kaktusId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KaktusAPIService ReadKaktusCaps", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kaktusId string

		resp, httpRes, err := apiClient.KaktusAPI.ReadKaktusCaps(context.Background(), kaktusId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KaktusAPIService UpdateKaktus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kaktusId string

		resp, httpRes, err := apiClient.KaktusAPI.UpdateKaktus(context.Background(), kaktusId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
