/*
Kowabunga API documentation

Kvm Orchestrator With A BUNch of Goods Added

API version: 0.52.5
Contact: maintainers@kowabunga.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kowabunga

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KawaiiFirewallEgressRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KawaiiFirewallEgressRule{}

// KawaiiFirewallEgressRule A Kawaii public firewall egress rule.
type KawaiiFirewallEgressRule struct {
	// The destination IP or CIDR to accept/drop public traffic to.
	Destination *string `json:"destination,omitempty"`
	// The transport layer protocol to accept/drop public traffic to.
	Protocol *string `json:"protocol,omitempty"`
	// The port (or list of ports) to accept/drop public traffic from. Ranges are accepted. Format is a-b,c-d (e.g. 443; 22,80,443; 80,443,3000-3005).
	Ports string `json:"ports"`
}

type _KawaiiFirewallEgressRule KawaiiFirewallEgressRule

// NewKawaiiFirewallEgressRule instantiates a new KawaiiFirewallEgressRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKawaiiFirewallEgressRule(ports string) *KawaiiFirewallEgressRule {
	this := KawaiiFirewallEgressRule{}
	var destination string = "0.0.0.0/0"
	this.Destination = &destination
	var protocol string = "tcp"
	this.Protocol = &protocol
	this.Ports = ports
	return &this
}

// NewKawaiiFirewallEgressRuleWithDefaults instantiates a new KawaiiFirewallEgressRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKawaiiFirewallEgressRuleWithDefaults() *KawaiiFirewallEgressRule {
	this := KawaiiFirewallEgressRule{}
	var destination string = "0.0.0.0/0"
	this.Destination = &destination
	var protocol string = "tcp"
	this.Protocol = &protocol
	return &this
}

// GetDestination returns the Destination field value if set, zero value otherwise.
func (o *KawaiiFirewallEgressRule) GetDestination() string {
	if o == nil || IsNil(o.Destination) {
		var ret string
		return ret
	}
	return *o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KawaiiFirewallEgressRule) GetDestinationOk() (*string, bool) {
	if o == nil || IsNil(o.Destination) {
		return nil, false
	}
	return o.Destination, true
}

// HasDestination returns a boolean if a field has been set.
func (o *KawaiiFirewallEgressRule) HasDestination() bool {
	if o != nil && !IsNil(o.Destination) {
		return true
	}

	return false
}

// SetDestination gets a reference to the given string and assigns it to the Destination field.
func (o *KawaiiFirewallEgressRule) SetDestination(v string) {
	o.Destination = &v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *KawaiiFirewallEgressRule) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KawaiiFirewallEgressRule) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *KawaiiFirewallEgressRule) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *KawaiiFirewallEgressRule) SetProtocol(v string) {
	o.Protocol = &v
}

// GetPorts returns the Ports field value
func (o *KawaiiFirewallEgressRule) GetPorts() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ports
}

// GetPortsOk returns a tuple with the Ports field value
// and a boolean to check if the value has been set.
func (o *KawaiiFirewallEgressRule) GetPortsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ports, true
}

// SetPorts sets field value
func (o *KawaiiFirewallEgressRule) SetPorts(v string) {
	o.Ports = v
}

func (o KawaiiFirewallEgressRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KawaiiFirewallEgressRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Destination) {
		toSerialize["destination"] = o.Destination
	}
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	toSerialize["ports"] = o.Ports
	return toSerialize, nil
}

func (o *KawaiiFirewallEgressRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ports",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKawaiiFirewallEgressRule := _KawaiiFirewallEgressRule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKawaiiFirewallEgressRule)

	if err != nil {
		return err
	}

	*o = KawaiiFirewallEgressRule(varKawaiiFirewallEgressRule)

	return err
}

type NullableKawaiiFirewallEgressRule struct {
	value *KawaiiFirewallEgressRule
	isSet bool
}

func (v NullableKawaiiFirewallEgressRule) Get() *KawaiiFirewallEgressRule {
	return v.value
}

func (v *NullableKawaiiFirewallEgressRule) Set(val *KawaiiFirewallEgressRule) {
	v.value = val
	v.isSet = true
}

func (v NullableKawaiiFirewallEgressRule) IsSet() bool {
	return v.isSet
}

func (v *NullableKawaiiFirewallEgressRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKawaiiFirewallEgressRule(val *KawaiiFirewallEgressRule) *NullableKawaiiFirewallEgressRule {
	return &NullableKawaiiFirewallEgressRule{value: val, isSet: true}
}

func (v NullableKawaiiFirewallEgressRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKawaiiFirewallEgressRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


