/*
Kowabunga API

Kvm Orchestrator With A BUNch of Goods Added

API version: 0.53.1
Contact: maintainers@kowabunga.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kowabunga

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiErrorUnauthorized type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiErrorUnauthorized{}

// ApiErrorUnauthorized struct for ApiErrorUnauthorized
type ApiErrorUnauthorized struct {
	Status int32 `json:"status"`
	Error string `json:"error"`
	Reason string `json:"reason"`
}

type _ApiErrorUnauthorized ApiErrorUnauthorized

// NewApiErrorUnauthorized instantiates a new ApiErrorUnauthorized object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiErrorUnauthorized(status int32, error_ string, reason string) *ApiErrorUnauthorized {
	this := ApiErrorUnauthorized{}
	this.Status = status
	this.Error = error_
	this.Reason = reason
	return &this
}

// NewApiErrorUnauthorizedWithDefaults instantiates a new ApiErrorUnauthorized object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiErrorUnauthorizedWithDefaults() *ApiErrorUnauthorized {
	this := ApiErrorUnauthorized{}
	return &this
}

// GetStatus returns the Status field value
func (o *ApiErrorUnauthorized) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ApiErrorUnauthorized) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ApiErrorUnauthorized) SetStatus(v int32) {
	o.Status = v
}

// GetError returns the Error field value
func (o *ApiErrorUnauthorized) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ApiErrorUnauthorized) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ApiErrorUnauthorized) SetError(v string) {
	o.Error = v
}

// GetReason returns the Reason field value
func (o *ApiErrorUnauthorized) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *ApiErrorUnauthorized) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *ApiErrorUnauthorized) SetReason(v string) {
	o.Reason = v
}

func (o ApiErrorUnauthorized) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiErrorUnauthorized) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["error"] = o.Error
	toSerialize["reason"] = o.Reason
	return toSerialize, nil
}

func (o *ApiErrorUnauthorized) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"error",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiErrorUnauthorized := _ApiErrorUnauthorized{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiErrorUnauthorized)

	if err != nil {
		return err
	}

	*o = ApiErrorUnauthorized(varApiErrorUnauthorized)

	return err
}

type NullableApiErrorUnauthorized struct {
	value *ApiErrorUnauthorized
	isSet bool
}

func (v NullableApiErrorUnauthorized) Get() *ApiErrorUnauthorized {
	return v.value
}

func (v *NullableApiErrorUnauthorized) Set(val *ApiErrorUnauthorized) {
	v.value = val
	v.isSet = true
}

func (v NullableApiErrorUnauthorized) IsSet() bool {
	return v.isSet
}

func (v *NullableApiErrorUnauthorized) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiErrorUnauthorized(val *ApiErrorUnauthorized) *NullableApiErrorUnauthorized {
	return &NullableApiErrorUnauthorized{value: val, isSet: true}
}

func (v NullableApiErrorUnauthorized) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiErrorUnauthorized) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


