/*
Kowabunga API

Kvm Orchestrator With A BUNch of Goods Added

API version: 0.53.2
Contact: maintainers@kowabunga.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kowabunga

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KawaiiDNatRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KawaiiDNatRule{}

// KawaiiDNatRule A Kawaii public firewall destination NAT rule.
type KawaiiDNatRule struct {
	// Target private IP address to forward public traffic to.
	Destination string `json:"destination"`
	// The transport layer protocol to forward public traffic to.
	Protocol *string `json:"protocol,omitempty"`
	// The port (or list of ports) to forward public traffic from. Ranges are accepted. Format is a-b,c-d (e.g. 443; 22,80,443; 80,443,3000-3005).
	Ports string `json:"ports"`
}

type _KawaiiDNatRule KawaiiDNatRule

// NewKawaiiDNatRule instantiates a new KawaiiDNatRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKawaiiDNatRule(destination string, ports string) *KawaiiDNatRule {
	this := KawaiiDNatRule{}
	this.Destination = destination
	var protocol string = "tcp"
	this.Protocol = &protocol
	this.Ports = ports
	return &this
}

// NewKawaiiDNatRuleWithDefaults instantiates a new KawaiiDNatRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKawaiiDNatRuleWithDefaults() *KawaiiDNatRule {
	this := KawaiiDNatRule{}
	var protocol string = "tcp"
	this.Protocol = &protocol
	return &this
}

// GetDestination returns the Destination field value
func (o *KawaiiDNatRule) GetDestination() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value
// and a boolean to check if the value has been set.
func (o *KawaiiDNatRule) GetDestinationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Destination, true
}

// SetDestination sets field value
func (o *KawaiiDNatRule) SetDestination(v string) {
	o.Destination = v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *KawaiiDNatRule) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KawaiiDNatRule) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *KawaiiDNatRule) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *KawaiiDNatRule) SetProtocol(v string) {
	o.Protocol = &v
}

// GetPorts returns the Ports field value
func (o *KawaiiDNatRule) GetPorts() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ports
}

// GetPortsOk returns a tuple with the Ports field value
// and a boolean to check if the value has been set.
func (o *KawaiiDNatRule) GetPortsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ports, true
}

// SetPorts sets field value
func (o *KawaiiDNatRule) SetPorts(v string) {
	o.Ports = v
}

func (o KawaiiDNatRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KawaiiDNatRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["destination"] = o.Destination
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	toSerialize["ports"] = o.Ports
	return toSerialize, nil
}

func (o *KawaiiDNatRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"destination",
		"ports",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKawaiiDNatRule := _KawaiiDNatRule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKawaiiDNatRule)

	if err != nil {
		return err
	}

	*o = KawaiiDNatRule(varKawaiiDNatRule)

	return err
}

type NullableKawaiiDNatRule struct {
	value *KawaiiDNatRule
	isSet bool
}

func (v NullableKawaiiDNatRule) Get() *KawaiiDNatRule {
	return v.value
}

func (v *NullableKawaiiDNatRule) Set(val *KawaiiDNatRule) {
	v.value = val
	v.isSet = true
}

func (v NullableKawaiiDNatRule) IsSet() bool {
	return v.isSet
}

func (v *NullableKawaiiDNatRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKawaiiDNatRule(val *KawaiiDNatRule) *NullableKawaiiDNatRule {
	return &NullableKawaiiDNatRule{value: val, isSet: true}
}

func (v NullableKawaiiDNatRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKawaiiDNatRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


