/*
Kowabunga API documentation

Kvm Orchestrator With A BUNch of Goods Added

API version: 0.52.5
Contact: maintainers@kowabunga.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kowabunga

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiErrorForbidden type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiErrorForbidden{}

// ApiErrorForbidden struct for ApiErrorForbidden
type ApiErrorForbidden struct {
	Status int32 `json:"status"`
	Error string `json:"error"`
	Reason string `json:"reason"`
}

type _ApiErrorForbidden ApiErrorForbidden

// NewApiErrorForbidden instantiates a new ApiErrorForbidden object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiErrorForbidden(status int32, error_ string, reason string) *ApiErrorForbidden {
	this := ApiErrorForbidden{}
	this.Status = status
	this.Error = error_
	this.Reason = reason
	return &this
}

// NewApiErrorForbiddenWithDefaults instantiates a new ApiErrorForbidden object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiErrorForbiddenWithDefaults() *ApiErrorForbidden {
	this := ApiErrorForbidden{}
	return &this
}

// GetStatus returns the Status field value
func (o *ApiErrorForbidden) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ApiErrorForbidden) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ApiErrorForbidden) SetStatus(v int32) {
	o.Status = v
}

// GetError returns the Error field value
func (o *ApiErrorForbidden) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ApiErrorForbidden) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ApiErrorForbidden) SetError(v string) {
	o.Error = v
}

// GetReason returns the Reason field value
func (o *ApiErrorForbidden) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *ApiErrorForbidden) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *ApiErrorForbidden) SetReason(v string) {
	o.Reason = v
}

func (o ApiErrorForbidden) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiErrorForbidden) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["error"] = o.Error
	toSerialize["reason"] = o.Reason
	return toSerialize, nil
}

func (o *ApiErrorForbidden) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"error",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiErrorForbidden := _ApiErrorForbidden{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiErrorForbidden)

	if err != nil {
		return err
	}

	*o = ApiErrorForbidden(varApiErrorForbidden)

	return err
}

type NullableApiErrorForbidden struct {
	value *ApiErrorForbidden
	isSet bool
}

func (v NullableApiErrorForbidden) Get() *ApiErrorForbidden {
	return v.value
}

func (v *NullableApiErrorForbidden) Set(val *ApiErrorForbidden) {
	v.value = val
	v.isSet = true
}

func (v NullableApiErrorForbidden) IsSet() bool {
	return v.isSet
}

func (v *NullableApiErrorForbidden) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiErrorForbidden(val *ApiErrorForbidden) *NullableApiErrorForbidden {
	return &NullableApiErrorForbidden{value: val, isSet: true}
}

func (v NullableApiErrorForbidden) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiErrorForbidden) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


