/*
Kowabunga API

Kvm Orchestrator With A BUNch of Goods Added

API version: 0.53.2
Contact: maintainers@kowabunga.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kowabunga

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InstanceRemoteAccess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceRemoteAccess{}

// InstanceRemoteAccess A virtual machine instance remote access characteristics.
type InstanceRemoteAccess struct {
	// The virtual machine instance remote access URL.
	Url string `json:"url"`
}

type _InstanceRemoteAccess InstanceRemoteAccess

// NewInstanceRemoteAccess instantiates a new InstanceRemoteAccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceRemoteAccess(url string) *InstanceRemoteAccess {
	this := InstanceRemoteAccess{}
	this.Url = url
	return &this
}

// NewInstanceRemoteAccessWithDefaults instantiates a new InstanceRemoteAccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceRemoteAccessWithDefaults() *InstanceRemoteAccess {
	this := InstanceRemoteAccess{}
	return &this
}

// GetUrl returns the Url field value
func (o *InstanceRemoteAccess) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *InstanceRemoteAccess) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *InstanceRemoteAccess) SetUrl(v string) {
	o.Url = v
}

func (o InstanceRemoteAccess) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceRemoteAccess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *InstanceRemoteAccess) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceRemoteAccess := _InstanceRemoteAccess{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstanceRemoteAccess)

	if err != nil {
		return err
	}

	*o = InstanceRemoteAccess(varInstanceRemoteAccess)

	return err
}

type NullableInstanceRemoteAccess struct {
	value *InstanceRemoteAccess
	isSet bool
}

func (v NullableInstanceRemoteAccess) Get() *InstanceRemoteAccess {
	return v.value
}

func (v *NullableInstanceRemoteAccess) Set(val *InstanceRemoteAccess) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceRemoteAccess) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceRemoteAccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceRemoteAccess(val *InstanceRemoteAccess) *NullableInstanceRemoteAccess {
	return &NullableInstanceRemoteAccess{value: val, isSet: true}
}

func (v NullableInstanceRemoteAccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceRemoteAccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


