/*
Kowabunga API

Kvm Orchestrator With A BUNch of Goods Added

API version: 0.53.1
Contact: maintainers@kowabunga.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kowabunga

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KawaiiVpcNetIpZone type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KawaiiVpcNetIpZone{}

// KawaiiVpcNetIpZone A Kawaii VPC Network IP zone settings.
type KawaiiVpcNetIpZone struct {
	// The Kawaii zone name (read-only).
	Zone string `json:"zone"`
	// The Kawaii zone gateway private IP address in VPC peered subnet  (read-only).
	Private string `json:"private"`
}

type _KawaiiVpcNetIpZone KawaiiVpcNetIpZone

// NewKawaiiVpcNetIpZone instantiates a new KawaiiVpcNetIpZone object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKawaiiVpcNetIpZone(zone string, private string) *KawaiiVpcNetIpZone {
	this := KawaiiVpcNetIpZone{}
	this.Zone = zone
	this.Private = private
	return &this
}

// NewKawaiiVpcNetIpZoneWithDefaults instantiates a new KawaiiVpcNetIpZone object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKawaiiVpcNetIpZoneWithDefaults() *KawaiiVpcNetIpZone {
	this := KawaiiVpcNetIpZone{}
	return &this
}

// GetZone returns the Zone field value
func (o *KawaiiVpcNetIpZone) GetZone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zone
}

// GetZoneOk returns a tuple with the Zone field value
// and a boolean to check if the value has been set.
func (o *KawaiiVpcNetIpZone) GetZoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zone, true
}

// SetZone sets field value
func (o *KawaiiVpcNetIpZone) SetZone(v string) {
	o.Zone = v
}

// GetPrivate returns the Private field value
func (o *KawaiiVpcNetIpZone) GetPrivate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Private
}

// GetPrivateOk returns a tuple with the Private field value
// and a boolean to check if the value has been set.
func (o *KawaiiVpcNetIpZone) GetPrivateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Private, true
}

// SetPrivate sets field value
func (o *KawaiiVpcNetIpZone) SetPrivate(v string) {
	o.Private = v
}

func (o KawaiiVpcNetIpZone) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KawaiiVpcNetIpZone) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["zone"] = o.Zone
	toSerialize["private"] = o.Private
	return toSerialize, nil
}

func (o *KawaiiVpcNetIpZone) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"zone",
		"private",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKawaiiVpcNetIpZone := _KawaiiVpcNetIpZone{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKawaiiVpcNetIpZone)

	if err != nil {
		return err
	}

	*o = KawaiiVpcNetIpZone(varKawaiiVpcNetIpZone)

	return err
}

type NullableKawaiiVpcNetIpZone struct {
	value *KawaiiVpcNetIpZone
	isSet bool
}

func (v NullableKawaiiVpcNetIpZone) Get() *KawaiiVpcNetIpZone {
	return v.value
}

func (v *NullableKawaiiVpcNetIpZone) Set(val *KawaiiVpcNetIpZone) {
	v.value = val
	v.isSet = true
}

func (v NullableKawaiiVpcNetIpZone) IsSet() bool {
	return v.isSet
}

func (v *NullableKawaiiVpcNetIpZone) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKawaiiVpcNetIpZone(val *KawaiiVpcNetIpZone) *NullableKawaiiVpcNetIpZone {
	return &NullableKawaiiVpcNetIpZone{value: val, isSet: true}
}

func (v NullableKawaiiVpcNetIpZone) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKawaiiVpcNetIpZone) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


